runtime: nodejs
env: flex

env_variables:
  DATABASE_URI:mongodb://ecouser:rV9WGTlFl7hlghak@cluster0-shard-00-00.jtcjr.mongodb.net:27017,cluster0-shard-00-01.jtcjr.mongodb.net:27017,cluster0-shard-00-0$
  APP_ID:ecoapp
  MASTER_KEY:ZDE3YTgwMzliYzEyN2_9
  SERVER_URL:http://ecobalance.life:1337/parse
