runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  # DATABASE_URI: mongodb://ecouser:YjRmZmZhMjA5MzdjNm_9@cluster0-shard-00-00.jtcjr.mongodb.net:27017,cluster0-shard-00-01.jtcjr.mongodb.net:27017,cluster0-shard-00-02.jtcjr.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-hpdlct-shard-0&authSource=admin&retryWrites=true&w=majority
  APP_ID: ecoapp
  MASTER_KEY: MTdmNzRiMmY3MmNiMT_9
  SERVER_URL: http://localhost:1337/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:
