runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  # DATABASE_URI:
  # APP_ID:
  # MASTER_KEY:
  # SERVER_URL:
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:
